name: Daily Commit

on:
  schedule:
    - cron: '55 9 * * *'  # Runs daily at 6:12 AM UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: 23f1000897@ds.study.iitm.ac.in
      - name: Make a daily update
        run: |
          echo "Last run: $(date -u)" > last-run.txt
          git config user.name "github-actions[bot]"
          git config user.email "borarohak@gmail.com"
          git add .
          git commit -m "Daily commit - $(date -u)"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
