name: Email Action Example

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1000897@ds.study.iitm.ac.in
        run: echo "Hello, world!"
