name: Daily ISS Tracker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:     # Manual trigger for testing

jobs:
  fetch_iss_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch ISS data
        run: |
          mkdir -p data
          curl http://api.open-notify.org/iss-now.json -o "data/$(date +%F).json"

      - name: Commit and push data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Add ISS data for $(date +%F)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push
